apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uber-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/celtic01/uber-app
    path: helm
    helm:
      valueFiles:
        - Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
